Repository wecode-bootcamp-korea/31-2nd-OldVintage-backend, pull requests merged in 2022-04, with the labels that each got.

#2 모델링 수정 (추가)
  products/migrations/0005_rename_grapes_product_grape.py
  products/models.py
  reviews/migrations/0002_alter_image_image_url.py
  reviews/models.py
Labels: Status: 리뷰 요청

#3 모델링 수정 (추가)
  products/migrations/0006_pairing_image_url_product_image_url.py
  products/migrations/0007_alter_pairing_image_url_alter_product_image_url.py
  products/models.py
  users/migrations/0002_alter_user_kakao_id.py
  users/models.py
Labels: Status: Accepted

#5 모델링 수정(추가3)
  users/migrations/0003_remove_user_password_alter_user_kakao_id.py
  users/models.py
Labels: Status: 수정 요청

#6 ProductListView (1차 중간 리뷰 요청)
  oldvintage/urls.py
  products/tests.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#7 [박광수]"Add: Kakao Login View 작성, login test 작성"
  oldvintage/__init__.py
  oldvintage/settings.py
  oldvintage/urls.py
  users/tests.py
  users/urls.py
  users/utils.py
  users/views.py
Labels: Status: 리뷰 요청

#9 ProductListView (통신 후 추가 수정)
  products/views.py
Labels: Status: 리뷰 요청

#11 ProductReviewview
  products/tests.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#13 "Modify: 카카오 로그인 절차간소화에따른 코드 수정, 테스트코드 수정"
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#14 "Add: Product Detail View작성, 테스트코드 작성"
  oldvintage/settings.py
  products/tests.py
  products/urls.py
  products/views.py
  users/tests.py
  users/views.py
Labels: Status: 리뷰 요청

#12 SearchView (Navbar 검색 기능)
  products/tests.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#10 ReviewView
  cores/storage.py
  oldvintage/settings.py
  oldvintage/urls.py
  products/tests.py
  products/views.py
  reviews/tests.py
  reviews/urls.py
  reviews/views.py
  users/utils.py
Labels: Status: 리뷰 요청

#15 Modify: requirements.txt 최신화
  requirements.txt
Labels: Status: Accepted

#16 Unit test fail 항목 수정
  products/tests.py
  reviews/tests.py
Labels: Status: 리뷰 요청
